require: rubocop-rails

inherit_from: .rubocop_exclusions.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - '**/bin/*'
    - '**/db/migrate/*'
    - '**/db/schema.rb'
    - '**/Gemfile'
    - '**/Gemfile.lock'
    - '**/Rakefile'
    - '**/rails'
    - '**/dummy/**/*'
    - '**/vendor/**/*'
    - '**/spec_helper.rb'
    - '**/rails_helper.rb'
